Serilog:
  MinimumLevel:
    Default: Debug
    Override:
      Microsoft: Information
      Microsoft.AspNetCore: Information
      Microsoft.EntityFrameworkCore: Information
      Microsoft.EntityFrameworkCore.Database.Command: Information
  WriteTo:
    - Name: Console
      Args:
        outputTemplate: "[{Timestamp:HH:mm:ss} {Level:u3}] {Message:lj} {Properties:j}{NewLine}{Exception}"
